### ISSUE TITLE
VST Plugins has no effect on Apple Silicon

### ISSUE THREAD

**Issue by jhmk** [damiangr/Rigkeeper#1]
Hi,

I'm running MacOS 11.4, Logic Pro 10.6.2  on a Macbook Pro with M1.
I can activate the Plugin in the Plugin Manager of Logic but it has no effect in changing the sound of my Input source.

Let me know if I can provide you with any kinds of Log files etc. in case you like to work on this (I know there aren't that much user out there with my setup).

Best

**Comment by damiangr** [comment]
This plugin is only for storing Kemper Rig Files within the DAW session. It won't change the sound of the track.
